name: Stintern

baseurl: "/stintern-ui/"

markdown: redcarpet
redcarpet:
  extensions: ["smart"]

exclude: [
  .git,
  .gitignore,
  .DS_Store,
  .sass-cache,
  bower.json
  readme.md,
  package.json,
  Gruntfile.js,
  bower_components,
  node_modules,
  scss,
]

excerpt_separator: <!--more-->